// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "../test_utils.mjs";
import * as Tagged_template_libJs from "./tagged_template_lib.js";

let q = Tagged_template_libJs.taggedTemplateLiteralAssert`hello ${"world"}`;

Mocha.describe("cross-directory consumer of relative @taggedTemplate", () => {
  Mocha.test("consumer in a subdirectory uses the @taggedTemplate external from a sibling-directory module", () => Test_utils.eq("File \"tagged_template_cross_dir_test.res\", line 9, characters 13-20", q, "hello 'world'"));
});

export {
  q,
}
/* q Not a pure module */
