// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function sum(a) {
  let len = a.length;
  if (len >= 4) {
    return -1;
  }
  switch (len) {
    case 0 :
      return 0;
    case 1 :
      return a[0];
    case 2 :
      let x = a[0];
      let y = a[1];
      return x + y | 0;
    case 3 :
      let x$1 = a[0];
      let y$1 = a[1];
      let z = a[2];
      return (x$1 + y$1 | 0) + z | 0;
  }
}

function describeLen(a) {
  let len = a.length;
  if (len >= 3) {
    return "many";
  }
  switch (len) {
    case 0 :
      return "empty";
    case 1 :
      return "one";
    case 2 :
      return "two";
  }
}

Mocha.describe("Pattern_match_array_test", () => {
  Mocha.test("array match by length", () => {
    Test_utils.eq("File \"pattern_match_array_test.res\", line 26, characters 7-14", sum([]), 0);
    Test_utils.eq("File \"pattern_match_array_test.res\", line 27, characters 7-14", sum([7]), 7);
    Test_utils.eq("File \"pattern_match_array_test.res\", line 28, characters 7-14", sum([
      1,
      2
    ]), 3);
    Test_utils.eq("File \"pattern_match_array_test.res\", line 29, characters 7-14", sum([
      1,
      2,
      3
    ]), 6);
    Test_utils.eq("File \"pattern_match_array_test.res\", line 30, characters 7-14", sum([
      1,
      2,
      3,
      4
    ]), -1);
  });
  Mocha.test("array match by length (wildcards)", () => {
    Test_utils.eq("File \"pattern_match_array_test.res\", line 34, characters 7-14", describeLen([]), "empty");
    Test_utils.eq("File \"pattern_match_array_test.res\", line 35, characters 7-14", describeLen([9]), "one");
    Test_utils.eq("File \"pattern_match_array_test.res\", line 36, characters 7-14", describeLen([
      1,
      2
    ]), "two");
    Test_utils.eq("File \"pattern_match_array_test.res\", line 37, characters 7-14", describeLen([
      1,
      2,
      3,
      4
    ]), "many");
  });
});

export {
  sum,
  describeLen,
}
/*  Not a pure module */
