// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function quadrant(p) {
  let x = p.x;
  if (x === 0) {
    if (p.y !== 0) {
      return "y-axis";
    } else {
      return "origin";
    }
  }
  let y = p.y;
  if (y !== 0) {
    if (x > 0 && y > 0) {
      return "q1";
    } else {
      return "other";
    }
  } else {
    return "x-axis";
  }
}

function bump(c) {
  let count = c.count;
  if (count !== 0) {
    return c.label + ":" + String(count);
  } else {
    return "start-" + c.label;
  }
}

function cmpPair(t) {
  let a = t[0];
  if (a === 0) {
    if (t[1] !== 0) {
      return "first-zero";
    } else {
      return "both-zero";
    }
  }
  let b = t[1];
  if (b !== 0) {
    if (a === b) {
      return "equal";
    } else {
      return "distinct";
    }
  } else {
    return "second-zero";
  }
}

Mocha.describe("Pattern_match_record_tuple_test", () => {
  Mocha.test("record field tests + guard", () => {
    Test_utils.eq("File \"pattern_match_record_tuple_test.res\", line 38, characters 7-14", quadrant({
      x: 0,
      y: 0
    }), "origin");
    Test_utils.eq("File \"pattern_match_record_tuple_test.res\", line 39, characters 7-14", quadrant({
      x: 0,
      y: 4
    }), "y-axis");
    Test_utils.eq("File \"pattern_match_record_tuple_test.res\", line 40, characters 7-14", quadrant({
      x: 4,
      y: 0
    }), "x-axis");
    Test_utils.eq("File \"pattern_match_record_tuple_test.res\", line 41, characters 7-14", quadrant({
      x: 1,
      y: 1
    }), "q1");
    Test_utils.eq("File \"pattern_match_record_tuple_test.res\", line 42, characters 7-14", quadrant({
      x: -1,
      y: 2
    }), "other");
  });
  Mocha.test("mutable record field match", () => {
    Test_utils.eq("File \"pattern_match_record_tuple_test.res\", line 46, characters 7-14", bump({
      count: 0,
      label: "a"
    }), "start-a");
    Test_utils.eq("File \"pattern_match_record_tuple_test.res\", line 47, characters 7-14", bump({
      count: 3,
      label: "b"
    }), "b:3");
  });
  Mocha.test("tuple match with guard", () => {
    Test_utils.eq("File \"pattern_match_record_tuple_test.res\", line 51, characters 7-14", cmpPair([
      0,
      0
    ]), "both-zero");
    Test_utils.eq("File \"pattern_match_record_tuple_test.res\", line 52, characters 7-14", cmpPair([
      0,
      7
    ]), "first-zero");
    Test_utils.eq("File \"pattern_match_record_tuple_test.res\", line 53, characters 7-14", cmpPair([
      7,
      0
    ]), "second-zero");
    Test_utils.eq("File \"pattern_match_record_tuple_test.res\", line 54, characters 7-14", cmpPair([
      5,
      5
    ]), "equal");
    Test_utils.eq("File \"pattern_match_record_tuple_test.res\", line 55, characters 7-14", cmpPair([
      5,
      6
    ]), "distinct");
  });
});

export {
  quadrant,
  bump,
  cmpPair,
}
/*  Not a pure module */
