// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function isOp(t) {
  return typeof t !== "object";
}

function rootVal(t) {
  return t._0;
}

function classify(x) {
  if ((x[0] - 1 | 0) > 2) {
    return "no";
  }
  switch (x[1]) {
    case "a" :
    case "b" :
      return "match";
    default:
      return "no";
  }
}

Mocha.describe("Pattern_match_orpat_test", () => {
  Mocha.test("or-pattern of constant constructors", () => {
    Test_utils.eq("File \"pattern_match_orpat_test.res\", line 34, characters 7-14", true, true);
    Test_utils.eq("File \"pattern_match_orpat_test.res\", line 35, characters 7-14", true, true);
    Test_utils.eq("File \"pattern_match_orpat_test.res\", line 36, characters 7-14", false, false);
  });
  Mocha.test("or-pattern binding shared variable", () => {
    Test_utils.eq("File \"pattern_match_orpat_test.res\", line 40, characters 7-14", 5, 5);
    Test_utils.eq("File \"pattern_match_orpat_test.res\", line 41, characters 7-14", 9, 9);
  });
  Mocha.test("or-patterns inside tuple columns", () => {
    Test_utils.eq("File \"pattern_match_orpat_test.res\", line 45, characters 7-14", classify([
      1,
      "a"
    ]), "match");
    Test_utils.eq("File \"pattern_match_orpat_test.res\", line 46, characters 7-14", classify([
      3,
      "b"
    ]), "match");
    Test_utils.eq("File \"pattern_match_orpat_test.res\", line 47, characters 7-14", classify([
      4,
      "a"
    ]), "no");
    Test_utils.eq("File \"pattern_match_orpat_test.res\", line 48, characters 7-14", classify([
      1,
      "c"
    ]), "no");
  });
});

export {
  isOp,
  rootVal,
  classify,
}
/*  Not a pure module */
