// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function classifyInt(x) {
  if (x >= 4) {
    if (x !== 100) {
      return "other";
    } else {
      return "hundred";
    }
  }
  if (x < -5) {
    return "other";
  }
  switch (x) {
    case -5 :
      return "neg5";
    case -4 :
    case -3 :
    case -2 :
    case -1 :
      return "other";
    case 0 :
      return "zero";
    case 1 :
    case 2 :
    case 3 :
      return "small";
  }
}

function classifyChar(c) {
  if (c !== 97) {
    if (c !== 101) {
      if (c !== 122) {
        return 0;
      } else {
        return 3;
      }
    } else {
      return 2;
    }
  } else {
    return 1;
  }
}

function classifyFloat(x) {
  if (x !== 0.0) {
    if (x !== 1.5) {
      if (x !== 2.5) {
        return "other";
      } else {
        return "twohalf";
      }
    } else {
      return "onehalf";
    }
  } else {
    return "zero";
  }
}

function classifyBig(b) {
  if (b !== 0n) {
    if (b !== 1n) {
      if (b !== 100n) {
        return "other";
      } else {
        return "hundred";
      }
    } else {
      return "one";
    }
  } else {
    return "zero";
  }
}

Mocha.describe("Pattern_match_constants_test", () => {
  Mocha.test("int switch with negatives, or-pattern and holes", () => {
    Test_utils.eq("File \"pattern_match_constants_test.res\", line 48, characters 7-14", classifyInt(-5), "neg5");
    Test_utils.eq("File \"pattern_match_constants_test.res\", line 49, characters 7-14", classifyInt(0), "zero");
    Test_utils.eq("File \"pattern_match_constants_test.res\", line 50, characters 7-14", classifyInt(1), "small");
    Test_utils.eq("File \"pattern_match_constants_test.res\", line 51, characters 7-14", classifyInt(2), "small");
    Test_utils.eq("File \"pattern_match_constants_test.res\", line 52, characters 7-14", classifyInt(3), "small");
    Test_utils.eq("File \"pattern_match_constants_test.res\", line 53, characters 7-14", classifyInt(100), "hundred");
    Test_utils.eq("File \"pattern_match_constants_test.res\", line 54, characters 7-14", classifyInt(4), "other");
    Test_utils.eq("File \"pattern_match_constants_test.res\", line 55, characters 7-14", classifyInt(-1), "other");
  });
  Mocha.test("char switch", () => {
    Test_utils.eq("File \"pattern_match_constants_test.res\", line 59, characters 7-14", classifyChar(/* 'a' */97), 1);
    Test_utils.eq("File \"pattern_match_constants_test.res\", line 60, characters 7-14", classifyChar(/* 'e' */101), 2);
    Test_utils.eq("File \"pattern_match_constants_test.res\", line 61, characters 7-14", classifyChar(/* 'z' */122), 3);
    Test_utils.eq("File \"pattern_match_constants_test.res\", line 62, characters 7-14", classifyChar(/* 'q' */113), 0);
  });
  Mocha.test("float switch (comparison sequence)", () => {
    Test_utils.eq("File \"pattern_match_constants_test.res\", line 66, characters 7-14", classifyFloat(0.0), "zero");
    Test_utils.eq("File \"pattern_match_constants_test.res\", line 67, characters 7-14", classifyFloat(1.5), "onehalf");
    Test_utils.eq("File \"pattern_match_constants_test.res\", line 68, characters 7-14", classifyFloat(2.5), "twohalf");
    Test_utils.eq("File \"pattern_match_constants_test.res\", line 69, characters 7-14", classifyFloat(9.9), "other");
  });
  Mocha.test("bigint switch (comparison sequence)", () => {
    Test_utils.eq("File \"pattern_match_constants_test.res\", line 73, characters 7-14", classifyBig(0n), "zero");
    Test_utils.eq("File \"pattern_match_constants_test.res\", line 74, characters 7-14", classifyBig(1n), "one");
    Test_utils.eq("File \"pattern_match_constants_test.res\", line 75, characters 7-14", classifyBig(100n), "hundred");
    Test_utils.eq("File \"pattern_match_constants_test.res\", line 76, characters 7-14", classifyBig(7n), "other");
  });
});

export {
  classifyInt,
  classifyChar,
  classifyFloat,
  classifyBig,
}
/*  Not a pure module */
