// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.mjs";

function area(s) {
  if (typeof s !== "object") {
    return 0.0;
  }
  switch (s.TAG) {
    case "Circle" :
      let r = s._0;
      return 3.0 * r * r;
    case "Square" :
      let side = s._0;
      return side * side;
    case "Rect" :
      return s._0 * s._1;
  }
}

let NotFound = /* @__PURE__ */Primitive_exceptions.create("Pattern_match_constructors_test.NotFound");

let Code = /* @__PURE__ */Primitive_exceptions.create("Pattern_match_constructors_test.Code");

function describeExn(e) {
  if (e.RE_EXN_ID === NotFound) {
    return "not-found";
  } else if (e.RE_EXN_ID === Code) {
    return "code:" + String(e._1);
  } else {
    return "other";
  }
}

function unwrap(m) {
  return m;
}

Mocha.describe("Pattern_match_constructors_test", () => {
  Mocha.test("exhaustive variant switch, mixed arities", () => {
    Test_utils.eq("File \"pattern_match_constructors_test.res\", line 42, characters 7-14", 0.0, 0.0);
    Test_utils.eq("File \"pattern_match_constructors_test.res\", line 43, characters 7-14", area({
      TAG: "Circle",
      _0: 2.0
    }), 12.0);
    Test_utils.eq("File \"pattern_match_constructors_test.res\", line 44, characters 7-14", area({
      TAG: "Square",
      _0: 3.0
    }), 9.0);
    Test_utils.eq("File \"pattern_match_constructors_test.res\", line 45, characters 7-14", area({
      TAG: "Rect",
      _0: 2.0,
      _1: 5.0
    }), 10.0);
  });
  Mocha.test("extension/exception constructor match", () => {
    Test_utils.eq("File \"pattern_match_constructors_test.res\", line 49, characters 7-14", describeExn({
      RE_EXN_ID: NotFound
    }), "not-found");
    Test_utils.eq("File \"pattern_match_constructors_test.res\", line 50, characters 7-14", describeExn({
      RE_EXN_ID: Code,
      _1: 5
    }), "code:5");
    Test_utils.eq("File \"pattern_match_constructors_test.res\", line 51, characters 7-14", describeExn({
      RE_EXN_ID: "Failure",
      _1: "x"
    }), "other");
  });
  Mocha.test("unboxed single constructor", () => Test_utils.eq("File \"pattern_match_constructors_test.res\", line 55, characters 7-14", 4.5, 4.5));
});

export {
  area,
  NotFound,
  Code,
  describeExn,
  unwrap,
}
/*  Not a pure module */
