// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Mocha from "mocha";
import * as Test_utils from "./test_utils.mjs";

function name(c) {
  if (typeof c !== "object") {
    if (c === "Blue") {
      return "blue";
    } else if (c === "Green") {
      return "green";
    } else {
      return "red";
    }
  }
  if (c.NAME === "Named") {
    return c.VAL;
  }
  let match = c.VAL;
  return String((match[0] + match[1] | 0) + match[2] | 0);
}

Mocha.describe("Pattern_match_polyvariant_test", () => {
  Mocha.test("polymorphic variant: constant tags", () => {
    Test_utils.eq("File \"pattern_match_polyvariant_test.res\", line 23, characters 7-14", name("Red"), "red");
    Test_utils.eq("File \"pattern_match_polyvariant_test.res\", line 24, characters 7-14", name("Green"), "green");
    Test_utils.eq("File \"pattern_match_polyvariant_test.res\", line 25, characters 7-14", name("Blue"), "blue");
  });
  Mocha.test("polymorphic variant: block tags", () => {
    Test_utils.eq("File \"pattern_match_polyvariant_test.res\", line 29, characters 7-14", name({
      NAME: "Rgb",
      VAL: [
        1,
        2,
        3
      ]
    }), "6");
    Test_utils.eq("File \"pattern_match_polyvariant_test.res\", line 30, characters 7-14", name({
      NAME: "Named",
      VAL: "teal"
    }), "teal");
  });
});

export {
  name,
}
/*  Not a pure module */
