// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tagged_template_libJs from "./tagged_template_lib.js";

function taggedTemplateLiteralAssert(prim0, prim1) {
  return Tagged_template_libJs.taggedTemplateLiteralAssert(prim0, ...prim1);
}

export {
  taggedTemplateLiteralAssert,
}
/* ./tagged_template_lib.js Not a pure module */
